Enable fragment result cache
prestodb/pbench pull request #12
Opened 2024-07-15 07:41 UTC by agrawalreetika

# Fragment result cache -
fragment cache -> disk = worker ram * 2 -> Effective cache size in config is disk * 0.95

2024-07-29 06:20 UTC, ethanyzhang requested changes

2024-07-29 06:20 UTC, ethanyzhang commented on clusters/templates/workers/config.properties
> +# fragment result cache
I talked to Reetika offline and she will make this section conditional

2024-07-29 21:15 UTC, ethanyzhang requested changes

2024-07-29 21:15 UTC, ethanyzhang commented on cmd/genconfig/config.go
> +	DataCacheEnabled              bool                 `json:"cache.enabled"`
Better to use `data_cache_enabled`, because `cache` is too general and may cause confusion with many cache types we have already.

2024-07-29 21:15 UTC, ethanyzhang commented on cmd/genconfig/config.go
> +	FragmentCacheEnabled          bool                 `json:"fragment-result-cache.enabled"`
To be consistent with the rest fields in this json file, I recommend using `fragment_result_cache_enabled`

2024-07-29 21:15 UTC, ethanyzhang commented on cmd/genconfig/config.go
> +	FragmentCacheEnabled          bool                 `json:"fragment-result-cache.enabled"`
Also can you help remove `RaptorXCacheEnabled` in line 15? I added that before but now it should be replaced by variables you added with this PR.

2024-07-29 21:15 UTC, ethanyzhang commented on clusters/templates/catalog/hive.properties
> +cache.enabled={{ .DataCacheEnabled }}
```suggestion
cache.enabled=true
```
It cannot be false now you are inside of this `if` construct.

2024-07-29 21:15 UTC, ethanyzhang commented on clusters/templates/workers/config.properties
> +fragment-result-cache.enabled={{ .FragmentCacheEnabled }}
```suggestion
fragment-result-cache.enabled=true
```

2024-07-29 21:15 UTC, ethanyzhang commented on clusters/2xlarge/config.json
>      "coordinator_instance_ebs_size": 1024,
Do we need the coordinator EBS size to remain this big?

2024-07-29 21:15 UTC, ethanyzhang commented on clusters/2xlarge/config.json
> +    "fragment-result-cache.enabled" : true,
nit: can we make the formatting consistent? same below
```suggestion
    "fragment-result-cache.enabled": true,
```

2024-07-29 21:15 UTC, ethanyzhang commented on cmd/genconfig/config.go
> +	c.FragmentResultCacheSizeGb = float32(c.MemoryPerNodeGb*2) * float32(0.95)
As I saw something like `fragment-result-cache.max-cache-size=471.19998GB` in the generated config, I started to think whether we should just round this value by adding a `math.Floor` or `math.Ceil` around this like some other values we are calculating here. But I will leave it to you.

2024-07-29 21:15 UTC, ethanyzhang commented on clusters/2xlarge/catalog/iceberg.properties
> +iceberg.parquet.metadata-cache-enabled=true
Now when I see the metadata configs above for hive, is there anything equivalent we need to set here for Iceberg?

2024-07-29 21:15 UTC, ethanyzhang commented on clusters/templates/catalog/iceberg.properties
> +cache.enabled={{ .DataCacheEnabled }}
```suggestion
cache.enabled=true
```

2024-07-30 03:24 UTC, agrawalreetika commented on clusters/2xlarge/config.json
>      "coordinator_instance_ebs_size": 1024,
@wanglinsong Should we reduce this as well to 50GB? Or what do you suggest for this?

2024-07-30 03:56 UTC, wanglinsong commented on clusters/2xlarge/config.json
>      "coordinator_instance_ebs_size": 1024,
50G should be good enough for the OS.

2024-07-30 05:33 UTC, ethanyzhang requested changes

2024-07-30 05:33 UTC, ethanyzhang commented on clusters/templates/catalog/iceberg-trino.properties
> +iceberg.parquet.metadata-cache-enabled=true
Actually I am not able to find this in Trino's source code..
https://github.com/search?q=repo%3Atrinodb%2Ftrino+metadata-cache-enabled&type=code

2024-07-30 05:37 UTC, ethanyzhang approved these changes

2024-07-30 05:39 UTC, merged